// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQe5hRhx1QeVSPww1JDmaiWNjGgW_-Ok8',
    appId: '1:211800926566:web:e02cdc6efceaca0a69c0a7',
    messagingSenderId: '211800926566',
    projectId: 'figma-4749d',
    authDomain: 'figma-4749d.firebaseapp.com',
    storageBucket: 'figma-4749d.appspot.com',
    measurementId: 'G-SCQBWJ730W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zY2Gg43UXu_4smKMogYfy4L4x_nb86Q',
    appId: '1:211800926566:android:fb27039c58f2934669c0a7',
    messagingSenderId: '211800926566',
    projectId: 'figma-4749d',
    storageBucket: 'figma-4749d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIHtwC43gO-iNJaiUoWAzsJUPFgjSBYng',
    appId: '1:211800926566:ios:36a88a8da606cbdf69c0a7',
    messagingSenderId: '211800926566',
    projectId: 'figma-4749d',
    storageBucket: 'figma-4749d.appspot.com',
    iosBundleId: 'com.example.figma1',
  );
}
